# Generated by Django 4.2.4 on 2023-08-08 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='downtime_last_day',
        ),
        migrations.RemoveField(
            model_name='report',
            name='downtime_last_hour',
        ),
        migrations.RemoveField(
            model_name='report',
            name='downtime_last_week',
        ),
        migrations.RemoveField(
            model_name='report',
            name='store',
        ),
        migrations.RemoveField(
            model_name='report',
            name='update_last_week',
        ),
        migrations.RemoveField(
            model_name='report',
            name='uptime_last_day',
        ),
        migrations.RemoveField(
            model_name='report',
            name='uptime_last_hour',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(default='', upload_to='reports', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
            preserve_default=False,
        ),
    ]
